name: create data

# on:
#   schedule:
#     - cron: '55 14 * * *'
on: 
  push:
    branches:
      - main
    

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # 일반적인 ci를 실행합니다.
      - name: CI
        run: |
          npm ci

      - name: NPM run
        run: |
          npm run dev
        env:
          OWNER: ${{ secrets.OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }} 
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_URL: ${{ secrets.GITHUB_URL }}
          DATA_DIR: ${{ secrets.DATA_DIR }}
